stages:
    - build
    - test
    - javadoc
    - deploy

image: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/gradle:8.5.0-jdk17"

variables:
  GRADLE_CMD: gradle -Dhttp.proxyHost=$PROXY_HTTP -Dhttp.proxyPort=$PROXY_PORT -Dhttps.proxyHost=$PROXY_HTTPS -Dhttps.proxyPort=$PROXY_PORT -Dhttps.proxyUser=$USERNAME -DHttps.proxyPassword=$ENT_PASSWORD

include:
  # build
    - '/templates-gitlab-ci/.gitlab-ci-build.yml'
  # test
    - '/templates-gitlab-ci/.gitlab-ci-test.yml'
  # quality (if merge to develop)
    #- '/templates-gitlab-ci/.gitlab-ci-quality.yml'
  # prod (if merge to main)
    #- '/templates-gitlab-ci/.gitlab-ci-prod.yml'


