unit_tests:
  stage: test
  needs:
    - build_application
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
  tags:
    - docker2
  allow_failure: true # Database doesn't exist
  script:
    - $GRADLE_CMD -Penv=qual clean
    - $GRADLE_CMD -Penv=qual test

sonarqube:
  stage: test
  needs:
    - unit_tests
  #rules:
  #  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
  tags:
    - docker2
  allow_failure: false
  script:
    - $GRADLE_CMD sonar -D sonar.login=$SONARQUBE_TOKEN -Penv=qual