build_application:
  stage: build
  image: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/gradle:8.5.0-jdk17"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
  tags:
    - docker2
  allow_failure: false
  script:
    - $GRADLE_CMD clean
    - $GRADLE_CMD build --refresh-dependencies
    - $GRADLE_CMD bootJar
  artifacts:
      name: museec-executables-$CI_COMMIT_SHA
      expire_in: 10 mins 0 sec
      paths:
         - build/libs/
  
  