unit_tests:
  stage: test
  image: "cache-ili.univ-artois.fr/proxy_cache/library/gradle:8.5.0-jdk17"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
  tags:
    - docker2
  allow_failure: false
  script:
    - gradle build --refresh-dependencies
    - gradle clean
    - gradle test