build_application:
  stage: build
  image: "reg-iutl.univ-artois.fr/proxy_cache/library/gradle:8.5.0-jdk17"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
  tags:
    - docker2
  allow_failure: false
  script:
    - gradle clean build --refresh-dependencies --debug
    - gradle bootJar
  artifacts:
      name: museec-executables-$CI_COMMIT_SHA
      expire_in: 10 mins 0 sec
      paths:
         - build/libs/
  
  