generate_jar:
  stage: deploy
  needs:
    - unit_tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME!="main"'  
  tags:
    - docker2
  allow_failure: false
  script:
    - $GRADLE_CMD -Penv=qual clean
    - $GRADLE_CMD -Penv=qual assemble --refresh-dependencies
    - $GRADLE_CMD -Penv=qual bootJar
  artifacts:
      name: museec-executables-$CI_COMMIT_SHA
      expire_in: 10 mins 0 sec
      paths:
         - build/libs/


generate_jar_prod:
  stage: deploy
  needs:
    - unit_tests_prod
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="main"'
  tags:
    - docker2
  allow_failure: false
  script:
    - $GRADLE_CMD -Penv=prod clean
    - $GRADLE_CMD -Penv=prod assemble --refresh-dependencies
    - $GRADLE_CMD -Penv=prod bootJar
  artifacts:
      name: museec-executables-$CI_COMMIT_SHA
      expire_in: 10 mins 0 sec
      paths:
         - build/libs/