build_application:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
  tags:
    - docker2
  allow_failure: false
  script:
    - $GRADLE_CMD -Penv=qual clean
    - $GRADLE_CMD -Penv=qual assemble --refresh-dependencies